//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bifrost.Message {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonMessage() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bifrost.Message.CommonMessage", typeof(CommonMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대해 현재 스레드의 CurrentUICulture 속성을
        ///   재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   _보다 커야합니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _보다커야합니다 {
            get {
                return ResourceManager.GetString("_보다커야합니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _와 _은 같아야 합니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _와_은같아야합니다 {
            get {
                return ResourceManager.GetString("_와_은같아야합니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _와 _은는 같을 수 없습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _와_은는같을수없습니다 {
            get {
                return ResourceManager.GetString("_와_은는같을수없습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _은 _보다 작거나 같아야 합니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _은_보다작거나같아야합니다 {
            get {
                return ResourceManager.GetString("_은_보다작거나같아야합니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _은 _보다 작아야 합니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _은_보다작아야합니다 {
            get {
                return ResourceManager.GetString("_은_보다작아야합니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _은 _보다 커야합니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _은_보다커야합니다 {
            get {
                return ResourceManager.GetString("_은_보다커야합니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _은 _보다 크거나 같아야 합니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _은_보다크거나같아야합니다 {
            get {
                return ResourceManager.GetString("_은_보다크거나같아야합니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _은는 _보다 큽니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _은는_보다큽니다 {
            get {
                return ResourceManager.GetString("_은는_보다큽니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _은는 필수입력 항목입니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _은는필수입력항목입니다 {
            get {
                return ResourceManager.GetString("_은는필수입력항목입니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _의 값이 중복되었습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _의값이중복되었습니다 {
            get {
                return ResourceManager.GetString("_의값이중복되었습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _이(가) 존재하지 않습니다.과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _이가존재하지않습니다 {
            get {
                return ResourceManager.GetString("_이가존재하지않습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _자료가 선택되어 있지 않습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _자료가선택되어있지않습니다 {
            get {
                return ResourceManager.GetString("_자료가선택되어있지않습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _자료가 선택되었습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _자료가선택되었습니다 {
            get {
                return ResourceManager.GetString("_자료가선택되었습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   _작업을 완료하였습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string _작업을완료하였습니다 {
            get {
                return ResourceManager.GetString("_작업을완료하였습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   기존에 등록된 자료가 있습니다\n삭제후 다시작업하시겠습니까과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 기존에등록된자료가있습니다삭제후다시작업하시겠습니까 {
            get {
                return ResourceManager.GetString("기존에등록된자료가있습니다삭제후다시작업하시겠습니까", resourceCulture);
            }
        }
        
        /// <summary>
        ///   등록되지 않은 자료입니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 등록되지않은자료입니다 {
            get {
                return ResourceManager.GetString("등록되지않은자료입니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경된 내용이 없습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 변경된내용이없습니다 {
            get {
                return ResourceManager.GetString("변경된내용이없습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   변경된 사항이 있습니다 저장하시겠습니까과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 변경된사항이있습니다저장하시겠습니까 {
            get {
                return ResourceManager.GetString("변경된사항이있습니다저장하시겠습니까", resourceCulture);
            }
        }
        
        /// <summary>
        ///   선택된 자료가 없습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 선택된자료가없습니다 {
            get {
                return ResourceManager.GetString("선택된자료가없습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   시작일자보다 종료일자가 클수 없습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 시작일자보다종료일자가클수없습니다 {
            get {
                return ResourceManager.GetString("시작일자보다종료일자가클수없습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 등록된 자료가 있습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 이미등록된자료가있습니다 {
            get {
                return ResourceManager.GetString("이미등록된자료가있습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   이미 진행중인작업이라 _할 수 없습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 이미진행중인작업이라_할수없습니다 {
            get {
                return ResourceManager.GetString("이미진행중인작업이라_할수없습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   입력형식이 올바르지 않습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 입력형식이올바르지않습니다 {
            get {
                return ResourceManager.GetString("입력형식이올바르지않습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자료가 정상적으로 삭제되었습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 자료가정상적으로삭제되었습니다 {
            get {
                return ResourceManager.GetString("자료가정상적으로삭제되었습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자료가 정상적으로 저장되었습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 자료가정상적으로저장되었습니다 {
            get {
                return ResourceManager.GetString("자료가정상적으로저장되었습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자료를 삭제하시겠습니까과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 자료를삭제하시겠습니까 {
            get {
                return ResourceManager.GetString("자료를삭제하시겠습니까", resourceCulture);
            }
        }
        
        /// <summary>
        ///   자료저장중 오류가 발생하였습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 자료저장중오류가발생하였습니다 {
            get {
                return ResourceManager.GetString("자료저장중오류가발생하였습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   작업을 정상적으로 처리하지 못했습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 작업을정상적으로처리하지못했습니다 {
            get {
                return ResourceManager.GetString("작업을정상적으로처리하지못했습니다", resourceCulture);
            }
        }
        
        /// <summary>
        ///   조건에 해당하는 내용이 없습니다과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string 조건에해당하는내용이없습니다 {
            get {
                return ResourceManager.GetString("조건에해당하는내용이없습니다", resourceCulture);
            }
        }
    }
}
