//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.42000에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace Jarvis.IAppUpdater {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AppUpdaterSoap", Namespace="http://tempuri.org/")]
    public partial class AppUpdater : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetBaseUpdateFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUpdateFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReportsUpdateFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback NeedReloadAllFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAppUpdaterUpdateListOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSubReportsUpdateFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveFileWithShellExecuteOperationCompleted;
        
        private System.Threading.SendOrPostCallback InitializationOperationCompleted;
        
        private System.Threading.SendOrPostCallback BeginUploadOperationCompleted;
        
        private System.Threading.SendOrPostCallback AppendChunkOperationCompleted;
        
        private System.Threading.SendOrPostCallback EndUploadOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveAllOperationCompleted;
        
        private System.Threading.SendOrPostCallback SaveAllWithFileInfoMstOperationCompleted;
        
        private System.Threading.SendOrPostCallback UploadFileOnlyOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFolderOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFilesOperationCompleted;
        
        private System.Threading.SendOrPostCallback BeginDownloadOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetChunkOperationCompleted;
        
        private System.Threading.SendOrPostCallback EndDownloadOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUploadSizeLimmitOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFileInfoMstOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFileInfoDetailSeqsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFileInfoDetailNamesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFileInfoDetailGuidNamesOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFileInfoDetailGuidsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteFileInfoDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteAllFileInfoDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFileInfoUrlOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetFileInfoDetailUrlOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AppUpdater() {
            this.Url = global::Jarvis.Properties.Settings.Default.Ether_IAppUpdater_AppUpdater;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetBaseUpdateFilesCompletedEventHandler GetBaseUpdateFilesCompleted;
        
        /// <remarks/>
        public event GetUpdateFilesCompletedEventHandler GetUpdateFilesCompleted;
        
        /// <remarks/>
        public event GetReportsUpdateFilesCompletedEventHandler GetReportsUpdateFilesCompleted;
        
        /// <remarks/>
        public event NeedReloadAllFilesCompletedEventHandler NeedReloadAllFilesCompleted;
        
        /// <remarks/>
        public event GetAppUpdaterUpdateListCompletedEventHandler GetAppUpdaterUpdateListCompleted;
        
        /// <remarks/>
        public event GetSubReportsUpdateFilesCompletedEventHandler GetSubReportsUpdateFilesCompleted;
        
        /// <remarks/>
        public event SaveFileWithShellExecuteCompletedEventHandler SaveFileWithShellExecuteCompleted;
        
        /// <remarks/>
        public event InitializationCompletedEventHandler InitializationCompleted;
        
        /// <remarks/>
        public event BeginUploadCompletedEventHandler BeginUploadCompleted;
        
        /// <remarks/>
        public event AppendChunkCompletedEventHandler AppendChunkCompleted;
        
        /// <remarks/>
        public event EndUploadCompletedEventHandler EndUploadCompleted;
        
        /// <remarks/>
        public event SaveCompletedEventHandler SaveCompleted;
        
        /// <remarks/>
        public event SaveAllCompletedEventHandler SaveAllCompleted;
        
        /// <remarks/>
        public event SaveAllWithFileInfoMstCompletedEventHandler SaveAllWithFileInfoMstCompleted;
        
        /// <remarks/>
        public event UploadFileOnlyCompletedEventHandler UploadFileOnlyCompleted;
        
        /// <remarks/>
        public event DeleteFolderCompletedEventHandler DeleteFolderCompleted;
        
        /// <remarks/>
        public event DeleteFilesCompletedEventHandler DeleteFilesCompleted;
        
        /// <remarks/>
        public event BeginDownloadCompletedEventHandler BeginDownloadCompleted;
        
        /// <remarks/>
        public event GetChunkCompletedEventHandler GetChunkCompleted;
        
        /// <remarks/>
        public event EndDownloadCompletedEventHandler EndDownloadCompleted;
        
        /// <remarks/>
        public event GetUploadSizeLimmitCompletedEventHandler GetUploadSizeLimmitCompleted;
        
        /// <remarks/>
        public event DeleteFileInfoMstCompletedEventHandler DeleteFileInfoMstCompleted;
        
        /// <remarks/>
        public event GetFileInfoDetailSeqsCompletedEventHandler GetFileInfoDetailSeqsCompleted;
        
        /// <remarks/>
        public event GetFileInfoDetailNamesCompletedEventHandler GetFileInfoDetailNamesCompleted;
        
        /// <remarks/>
        public event GetFileInfoDetailGuidNamesCompletedEventHandler GetFileInfoDetailGuidNamesCompleted;
        
        /// <remarks/>
        public event GetFileInfoDetailGuidsCompletedEventHandler GetFileInfoDetailGuidsCompleted;
        
        /// <remarks/>
        public event DeleteFileInfoDetailsCompletedEventHandler DeleteFileInfoDetailsCompleted;
        
        /// <remarks/>
        public event DeleteAllFileInfoDetailsCompletedEventHandler DeleteAllFileInfoDetailsCompleted;
        
        /// <remarks/>
        public event GetFileInfoUrlCompletedEventHandler GetFileInfoUrlCompleted;
        
        /// <remarks/>
        public event GetFileInfoDetailUrlCompletedEventHandler GetFileInfoDetailUrlCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBaseUpdateFiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetBaseUpdateFiles(string[] localFileInfos) {
            object[] results = this.Invoke("GetBaseUpdateFiles", new object[] {
                        localFileInfos});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBaseUpdateFilesAsync(string[] localFileInfos) {
            this.GetBaseUpdateFilesAsync(localFileInfos, null);
        }
        
        /// <remarks/>
        public void GetBaseUpdateFilesAsync(string[] localFileInfos, object userState) {
            if ((this.GetBaseUpdateFilesOperationCompleted == null)) {
                this.GetBaseUpdateFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBaseUpdateFilesOperationCompleted);
            }
            this.InvokeAsync("GetBaseUpdateFiles", new object[] {
                        localFileInfos}, this.GetBaseUpdateFilesOperationCompleted, userState);
        }
        
        private void OnGetBaseUpdateFilesOperationCompleted(object arg) {
            if ((this.GetBaseUpdateFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBaseUpdateFilesCompleted(this, new GetBaseUpdateFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUpdateFiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetUpdateFiles(string[] localFileInfos) {
            object[] results = this.Invoke("GetUpdateFiles", new object[] {
                        localFileInfos});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetUpdateFilesAsync(string[] localFileInfos) {
            this.GetUpdateFilesAsync(localFileInfos, null);
        }
        
        /// <remarks/>
        public void GetUpdateFilesAsync(string[] localFileInfos, object userState) {
            if ((this.GetUpdateFilesOperationCompleted == null)) {
                this.GetUpdateFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUpdateFilesOperationCompleted);
            }
            this.InvokeAsync("GetUpdateFiles", new object[] {
                        localFileInfos}, this.GetUpdateFilesOperationCompleted, userState);
        }
        
        private void OnGetUpdateFilesOperationCompleted(object arg) {
            if ((this.GetUpdateFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUpdateFilesCompleted(this, new GetUpdateFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetReportsUpdateFiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetReportsUpdateFiles(string[] localFileInfos) {
            object[] results = this.Invoke("GetReportsUpdateFiles", new object[] {
                        localFileInfos});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReportsUpdateFilesAsync(string[] localFileInfos) {
            this.GetReportsUpdateFilesAsync(localFileInfos, null);
        }
        
        /// <remarks/>
        public void GetReportsUpdateFilesAsync(string[] localFileInfos, object userState) {
            if ((this.GetReportsUpdateFilesOperationCompleted == null)) {
                this.GetReportsUpdateFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReportsUpdateFilesOperationCompleted);
            }
            this.InvokeAsync("GetReportsUpdateFiles", new object[] {
                        localFileInfos}, this.GetReportsUpdateFilesOperationCompleted, userState);
        }
        
        private void OnGetReportsUpdateFilesOperationCompleted(object arg) {
            if ((this.GetReportsUpdateFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReportsUpdateFilesCompleted(this, new GetReportsUpdateFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/NeedReloadAllFiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string NeedReloadAllFiles(string serverFolder) {
            object[] results = this.Invoke("NeedReloadAllFiles", new object[] {
                        serverFolder});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void NeedReloadAllFilesAsync(string serverFolder) {
            this.NeedReloadAllFilesAsync(serverFolder, null);
        }
        
        /// <remarks/>
        public void NeedReloadAllFilesAsync(string serverFolder, object userState) {
            if ((this.NeedReloadAllFilesOperationCompleted == null)) {
                this.NeedReloadAllFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnNeedReloadAllFilesOperationCompleted);
            }
            this.InvokeAsync("NeedReloadAllFiles", new object[] {
                        serverFolder}, this.NeedReloadAllFilesOperationCompleted, userState);
        }
        
        private void OnNeedReloadAllFilesOperationCompleted(object arg) {
            if ((this.NeedReloadAllFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.NeedReloadAllFilesCompleted(this, new NeedReloadAllFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetAppUpdaterUpdateList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetAppUpdaterUpdateList(string[] currentList) {
            object[] results = this.Invoke("GetAppUpdaterUpdateList", new object[] {
                        currentList});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAppUpdaterUpdateListAsync(string[] currentList) {
            this.GetAppUpdaterUpdateListAsync(currentList, null);
        }
        
        /// <remarks/>
        public void GetAppUpdaterUpdateListAsync(string[] currentList, object userState) {
            if ((this.GetAppUpdaterUpdateListOperationCompleted == null)) {
                this.GetAppUpdaterUpdateListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAppUpdaterUpdateListOperationCompleted);
            }
            this.InvokeAsync("GetAppUpdaterUpdateList", new object[] {
                        currentList}, this.GetAppUpdaterUpdateListOperationCompleted, userState);
        }
        
        private void OnGetAppUpdaterUpdateListOperationCompleted(object arg) {
            if ((this.GetAppUpdaterUpdateListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAppUpdaterUpdateListCompleted(this, new GetAppUpdaterUpdateListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetSubReportsUpdateFiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetSubReportsUpdateFiles(string[] localFileInfos) {
            object[] results = this.Invoke("GetSubReportsUpdateFiles", new object[] {
                        localFileInfos});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetSubReportsUpdateFilesAsync(string[] localFileInfos) {
            this.GetSubReportsUpdateFilesAsync(localFileInfos, null);
        }
        
        /// <remarks/>
        public void GetSubReportsUpdateFilesAsync(string[] localFileInfos, object userState) {
            if ((this.GetSubReportsUpdateFilesOperationCompleted == null)) {
                this.GetSubReportsUpdateFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSubReportsUpdateFilesOperationCompleted);
            }
            this.InvokeAsync("GetSubReportsUpdateFiles", new object[] {
                        localFileInfos}, this.GetSubReportsUpdateFilesOperationCompleted, userState);
        }
        
        private void OnGetSubReportsUpdateFilesOperationCompleted(object arg) {
            if ((this.GetSubReportsUpdateFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSubReportsUpdateFilesCompleted(this, new GetSubReportsUpdateFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveFileWithShellExecute", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SaveFileWithShellExecute(string instanceId, string targetFolder, bool gacRegister) {
            object[] results = this.Invoke("SaveFileWithShellExecute", new object[] {
                        instanceId,
                        targetFolder,
                        gacRegister});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SaveFileWithShellExecuteAsync(string instanceId, string targetFolder, bool gacRegister) {
            this.SaveFileWithShellExecuteAsync(instanceId, targetFolder, gacRegister, null);
        }
        
        /// <remarks/>
        public void SaveFileWithShellExecuteAsync(string instanceId, string targetFolder, bool gacRegister, object userState) {
            if ((this.SaveFileWithShellExecuteOperationCompleted == null)) {
                this.SaveFileWithShellExecuteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveFileWithShellExecuteOperationCompleted);
            }
            this.InvokeAsync("SaveFileWithShellExecute", new object[] {
                        instanceId,
                        targetFolder,
                        gacRegister}, this.SaveFileWithShellExecuteOperationCompleted, userState);
        }
        
        private void OnSaveFileWithShellExecuteOperationCompleted(object arg) {
            if ((this.SaveFileWithShellExecuteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveFileWithShellExecuteCompleted(this, new SaveFileWithShellExecuteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Initialization", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Initialization() {
            object[] results = this.Invoke("Initialization", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InitializationAsync() {
            this.InitializationAsync(null);
        }
        
        /// <remarks/>
        public void InitializationAsync(object userState) {
            if ((this.InitializationOperationCompleted == null)) {
                this.InitializationOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInitializationOperationCompleted);
            }
            this.InvokeAsync("Initialization", new object[0], this.InitializationOperationCompleted, userState);
        }
        
        private void OnInitializationOperationCompleted(object arg) {
            if ((this.InitializationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InitializationCompleted(this, new InitializationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BeginUpload", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int BeginUpload(string instanceId, string targetFileName, string SubFolder) {
            object[] results = this.Invoke("BeginUpload", new object[] {
                        instanceId,
                        targetFileName,
                        SubFolder});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void BeginUploadAsync(string instanceId, string targetFileName, string SubFolder) {
            this.BeginUploadAsync(instanceId, targetFileName, SubFolder, null);
        }
        
        /// <remarks/>
        public void BeginUploadAsync(string instanceId, string targetFileName, string SubFolder, object userState) {
            if ((this.BeginUploadOperationCompleted == null)) {
                this.BeginUploadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBeginUploadOperationCompleted);
            }
            this.InvokeAsync("BeginUpload", new object[] {
                        instanceId,
                        targetFileName,
                        SubFolder}, this.BeginUploadOperationCompleted, userState);
        }
        
        private void OnBeginUploadOperationCompleted(object arg) {
            if ((this.BeginUploadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BeginUploadCompleted(this, new BeginUploadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AppendChunk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int AppendChunk(string instanceId, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] buffer, int offset, int count) {
            object[] results = this.Invoke("AppendChunk", new object[] {
                        instanceId,
                        buffer,
                        offset,
                        count});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void AppendChunkAsync(string instanceId, byte[] buffer, int offset, int count) {
            this.AppendChunkAsync(instanceId, buffer, offset, count, null);
        }
        
        /// <remarks/>
        public void AppendChunkAsync(string instanceId, byte[] buffer, int offset, int count, object userState) {
            if ((this.AppendChunkOperationCompleted == null)) {
                this.AppendChunkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAppendChunkOperationCompleted);
            }
            this.InvokeAsync("AppendChunk", new object[] {
                        instanceId,
                        buffer,
                        offset,
                        count}, this.AppendChunkOperationCompleted, userState);
        }
        
        private void OnAppendChunkOperationCompleted(object arg) {
            if ((this.AppendChunkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AppendChunkCompleted(this, new AppendChunkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EndUpload", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int EndUpload(string instanceId) {
            object[] results = this.Invoke("EndUpload", new object[] {
                        instanceId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EndUploadAsync(string instanceId) {
            this.EndUploadAsync(instanceId, null);
        }
        
        /// <remarks/>
        public void EndUploadAsync(string instanceId, object userState) {
            if ((this.EndUploadOperationCompleted == null)) {
                this.EndUploadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEndUploadOperationCompleted);
            }
            this.InvokeAsync("EndUpload", new object[] {
                        instanceId}, this.EndUploadOperationCompleted, userState);
        }
        
        private void OnEndUploadOperationCompleted(object arg) {
            if ((this.EndUploadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EndUploadCompleted(this, new EndUploadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Save", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int Save(string instanceId) {
            object[] results = this.Invoke("Save", new object[] {
                        instanceId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SaveAsync(string instanceId) {
            this.SaveAsync(instanceId, null);
        }
        
        /// <remarks/>
        public void SaveAsync(string instanceId, object userState) {
            if ((this.SaveOperationCompleted == null)) {
                this.SaveOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveOperationCompleted);
            }
            this.InvokeAsync("Save", new object[] {
                        instanceId}, this.SaveOperationCompleted, userState);
        }
        
        private void OnSaveOperationCompleted(object arg) {
            if ((this.SaveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveCompleted(this, new SaveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveAll", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SaveAll(string instanceId) {
            object[] results = this.Invoke("SaveAll", new object[] {
                        instanceId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SaveAllAsync(string instanceId) {
            this.SaveAllAsync(instanceId, null);
        }
        
        /// <remarks/>
        public void SaveAllAsync(string instanceId, object userState) {
            if ((this.SaveAllOperationCompleted == null)) {
                this.SaveAllOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveAllOperationCompleted);
            }
            this.InvokeAsync("SaveAll", new object[] {
                        instanceId}, this.SaveAllOperationCompleted, userState);
        }
        
        private void OnSaveAllOperationCompleted(object arg) {
            if ((this.SaveAllCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveAllCompleted(this, new SaveAllCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SaveAllWithFileInfoMst", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int SaveAllWithFileInfoMst(string instanceId, int masterFileNum) {
            object[] results = this.Invoke("SaveAllWithFileInfoMst", new object[] {
                        instanceId,
                        masterFileNum});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void SaveAllWithFileInfoMstAsync(string instanceId, int masterFileNum) {
            this.SaveAllWithFileInfoMstAsync(instanceId, masterFileNum, null);
        }
        
        /// <remarks/>
        public void SaveAllWithFileInfoMstAsync(string instanceId, int masterFileNum, object userState) {
            if ((this.SaveAllWithFileInfoMstOperationCompleted == null)) {
                this.SaveAllWithFileInfoMstOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSaveAllWithFileInfoMstOperationCompleted);
            }
            this.InvokeAsync("SaveAllWithFileInfoMst", new object[] {
                        instanceId,
                        masterFileNum}, this.SaveAllWithFileInfoMstOperationCompleted, userState);
        }
        
        private void OnSaveAllWithFileInfoMstOperationCompleted(object arg) {
            if ((this.SaveAllWithFileInfoMstCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SaveAllWithFileInfoMstCompleted(this, new SaveAllWithFileInfoMstCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UploadFileOnly", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool UploadFileOnly(string targetServerFolder, string subPath, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] byte[] buffer) {
            object[] results = this.Invoke("UploadFileOnly", new object[] {
                        targetServerFolder,
                        subPath,
                        buffer});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void UploadFileOnlyAsync(string targetServerFolder, string subPath, byte[] buffer) {
            this.UploadFileOnlyAsync(targetServerFolder, subPath, buffer, null);
        }
        
        /// <remarks/>
        public void UploadFileOnlyAsync(string targetServerFolder, string subPath, byte[] buffer, object userState) {
            if ((this.UploadFileOnlyOperationCompleted == null)) {
                this.UploadFileOnlyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUploadFileOnlyOperationCompleted);
            }
            this.InvokeAsync("UploadFileOnly", new object[] {
                        targetServerFolder,
                        subPath,
                        buffer}, this.UploadFileOnlyOperationCompleted, userState);
        }
        
        private void OnUploadFileOnlyOperationCompleted(object arg) {
            if ((this.UploadFileOnlyCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UploadFileOnlyCompleted(this, new UploadFileOnlyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteFolder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteFolder(string targetServerFolder) {
            object[] results = this.Invoke("DeleteFolder", new object[] {
                        targetServerFolder});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteFolderAsync(string targetServerFolder) {
            this.DeleteFolderAsync(targetServerFolder, null);
        }
        
        /// <remarks/>
        public void DeleteFolderAsync(string targetServerFolder, object userState) {
            if ((this.DeleteFolderOperationCompleted == null)) {
                this.DeleteFolderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFolderOperationCompleted);
            }
            this.InvokeAsync("DeleteFolder", new object[] {
                        targetServerFolder}, this.DeleteFolderOperationCompleted, userState);
        }
        
        private void OnDeleteFolderOperationCompleted(object arg) {
            if ((this.DeleteFolderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFolderCompleted(this, new DeleteFolderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteFiles", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteFiles(string[] fullFiles) {
            object[] results = this.Invoke("DeleteFiles", new object[] {
                        fullFiles});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteFilesAsync(string[] fullFiles) {
            this.DeleteFilesAsync(fullFiles, null);
        }
        
        /// <remarks/>
        public void DeleteFilesAsync(string[] fullFiles, object userState) {
            if ((this.DeleteFilesOperationCompleted == null)) {
                this.DeleteFilesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFilesOperationCompleted);
            }
            this.InvokeAsync("DeleteFiles", new object[] {
                        fullFiles}, this.DeleteFilesOperationCompleted, userState);
        }
        
        private void OnDeleteFilesOperationCompleted(object arg) {
            if ((this.DeleteFilesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFilesCompleted(this, new DeleteFilesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BeginDownload", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] BeginDownload(string instanceId, string fileName) {
            object[] results = this.Invoke("BeginDownload", new object[] {
                        instanceId,
                        fileName});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void BeginDownloadAsync(string instanceId, string fileName) {
            this.BeginDownloadAsync(instanceId, fileName, null);
        }
        
        /// <remarks/>
        public void BeginDownloadAsync(string instanceId, string fileName, object userState) {
            if ((this.BeginDownloadOperationCompleted == null)) {
                this.BeginDownloadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBeginDownloadOperationCompleted);
            }
            this.InvokeAsync("BeginDownload", new object[] {
                        instanceId,
                        fileName}, this.BeginDownloadOperationCompleted, userState);
        }
        
        private void OnBeginDownloadOperationCompleted(object arg) {
            if ((this.BeginDownloadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BeginDownloadCompleted(this, new BeginDownloadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetChunk", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetChunk(string instanceId, int offset, int count, int fileSize, [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")] out byte[] buffer) {
            object[] results = this.Invoke("GetChunk", new object[] {
                        instanceId,
                        offset,
                        count,
                        fileSize});
            buffer = ((byte[])(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetChunkAsync(string instanceId, int offset, int count, int fileSize) {
            this.GetChunkAsync(instanceId, offset, count, fileSize, null);
        }
        
        /// <remarks/>
        public void GetChunkAsync(string instanceId, int offset, int count, int fileSize, object userState) {
            if ((this.GetChunkOperationCompleted == null)) {
                this.GetChunkOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetChunkOperationCompleted);
            }
            this.InvokeAsync("GetChunk", new object[] {
                        instanceId,
                        offset,
                        count,
                        fileSize}, this.GetChunkOperationCompleted, userState);
        }
        
        private void OnGetChunkOperationCompleted(object arg) {
            if ((this.GetChunkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetChunkCompleted(this, new GetChunkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EndDownload", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int EndDownload(string instanceId) {
            object[] results = this.Invoke("EndDownload", new object[] {
                        instanceId});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void EndDownloadAsync(string instanceId) {
            this.EndDownloadAsync(instanceId, null);
        }
        
        /// <remarks/>
        public void EndDownloadAsync(string instanceId, object userState) {
            if ((this.EndDownloadOperationCompleted == null)) {
                this.EndDownloadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEndDownloadOperationCompleted);
            }
            this.InvokeAsync("EndDownload", new object[] {
                        instanceId}, this.EndDownloadOperationCompleted, userState);
        }
        
        private void OnEndDownloadOperationCompleted(object arg) {
            if ((this.EndDownloadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EndDownloadCompleted(this, new EndDownloadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetUploadSizeLimmit", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetUploadSizeLimmit() {
            object[] results = this.Invoke("GetUploadSizeLimmit", new object[0]);
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetUploadSizeLimmitAsync() {
            this.GetUploadSizeLimmitAsync(null);
        }
        
        /// <remarks/>
        public void GetUploadSizeLimmitAsync(object userState) {
            if ((this.GetUploadSizeLimmitOperationCompleted == null)) {
                this.GetUploadSizeLimmitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUploadSizeLimmitOperationCompleted);
            }
            this.InvokeAsync("GetUploadSizeLimmit", new object[0], this.GetUploadSizeLimmitOperationCompleted, userState);
        }
        
        private void OnGetUploadSizeLimmitOperationCompleted(object arg) {
            if ((this.GetUploadSizeLimmitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUploadSizeLimmitCompleted(this, new GetUploadSizeLimmitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteFileInfoMst", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteFileInfoMst(string instanceId, string SubFolder, int masterFileNum) {
            object[] results = this.Invoke("DeleteFileInfoMst", new object[] {
                        instanceId,
                        SubFolder,
                        masterFileNum});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteFileInfoMstAsync(string instanceId, string SubFolder, int masterFileNum) {
            this.DeleteFileInfoMstAsync(instanceId, SubFolder, masterFileNum, null);
        }
        
        /// <remarks/>
        public void DeleteFileInfoMstAsync(string instanceId, string SubFolder, int masterFileNum, object userState) {
            if ((this.DeleteFileInfoMstOperationCompleted == null)) {
                this.DeleteFileInfoMstOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFileInfoMstOperationCompleted);
            }
            this.InvokeAsync("DeleteFileInfoMst", new object[] {
                        instanceId,
                        SubFolder,
                        masterFileNum}, this.DeleteFileInfoMstOperationCompleted, userState);
        }
        
        private void OnDeleteFileInfoMstOperationCompleted(object arg) {
            if ((this.DeleteFileInfoMstCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFileInfoMstCompleted(this, new DeleteFileInfoMstCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFileInfoDetailSeqs", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int[] GetFileInfoDetailSeqs(string instanceId, string SubFolder, int masterFileNum) {
            object[] results = this.Invoke("GetFileInfoDetailSeqs", new object[] {
                        instanceId,
                        SubFolder,
                        masterFileNum});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFileInfoDetailSeqsAsync(string instanceId, string SubFolder, int masterFileNum) {
            this.GetFileInfoDetailSeqsAsync(instanceId, SubFolder, masterFileNum, null);
        }
        
        /// <remarks/>
        public void GetFileInfoDetailSeqsAsync(string instanceId, string SubFolder, int masterFileNum, object userState) {
            if ((this.GetFileInfoDetailSeqsOperationCompleted == null)) {
                this.GetFileInfoDetailSeqsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFileInfoDetailSeqsOperationCompleted);
            }
            this.InvokeAsync("GetFileInfoDetailSeqs", new object[] {
                        instanceId,
                        SubFolder,
                        masterFileNum}, this.GetFileInfoDetailSeqsOperationCompleted, userState);
        }
        
        private void OnGetFileInfoDetailSeqsOperationCompleted(object arg) {
            if ((this.GetFileInfoDetailSeqsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFileInfoDetailSeqsCompleted(this, new GetFileInfoDetailSeqsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFileInfoDetailNames", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetFileInfoDetailNames(string instanceId, string SubFolder, int masterFileNum) {
            object[] results = this.Invoke("GetFileInfoDetailNames", new object[] {
                        instanceId,
                        SubFolder,
                        masterFileNum});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFileInfoDetailNamesAsync(string instanceId, string SubFolder, int masterFileNum) {
            this.GetFileInfoDetailNamesAsync(instanceId, SubFolder, masterFileNum, null);
        }
        
        /// <remarks/>
        public void GetFileInfoDetailNamesAsync(string instanceId, string SubFolder, int masterFileNum, object userState) {
            if ((this.GetFileInfoDetailNamesOperationCompleted == null)) {
                this.GetFileInfoDetailNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFileInfoDetailNamesOperationCompleted);
            }
            this.InvokeAsync("GetFileInfoDetailNames", new object[] {
                        instanceId,
                        SubFolder,
                        masterFileNum}, this.GetFileInfoDetailNamesOperationCompleted, userState);
        }
        
        private void OnGetFileInfoDetailNamesOperationCompleted(object arg) {
            if ((this.GetFileInfoDetailNamesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFileInfoDetailNamesCompleted(this, new GetFileInfoDetailNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFileInfoDetailGuidNames", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetFileInfoDetailGuidNames(string instanceId, string SubFolder, int masterFileNum) {
            object[] results = this.Invoke("GetFileInfoDetailGuidNames", new object[] {
                        instanceId,
                        SubFolder,
                        masterFileNum});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFileInfoDetailGuidNamesAsync(string instanceId, string SubFolder, int masterFileNum) {
            this.GetFileInfoDetailGuidNamesAsync(instanceId, SubFolder, masterFileNum, null);
        }
        
        /// <remarks/>
        public void GetFileInfoDetailGuidNamesAsync(string instanceId, string SubFolder, int masterFileNum, object userState) {
            if ((this.GetFileInfoDetailGuidNamesOperationCompleted == null)) {
                this.GetFileInfoDetailGuidNamesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFileInfoDetailGuidNamesOperationCompleted);
            }
            this.InvokeAsync("GetFileInfoDetailGuidNames", new object[] {
                        instanceId,
                        SubFolder,
                        masterFileNum}, this.GetFileInfoDetailGuidNamesOperationCompleted, userState);
        }
        
        private void OnGetFileInfoDetailGuidNamesOperationCompleted(object arg) {
            if ((this.GetFileInfoDetailGuidNamesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFileInfoDetailGuidNamesCompleted(this, new GetFileInfoDetailGuidNamesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFileInfoDetailGuids", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] GetFileInfoDetailGuids(string instanceId, string SubFolder, int masterFileNum) {
            object[] results = this.Invoke("GetFileInfoDetailGuids", new object[] {
                        instanceId,
                        SubFolder,
                        masterFileNum});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void GetFileInfoDetailGuidsAsync(string instanceId, string SubFolder, int masterFileNum) {
            this.GetFileInfoDetailGuidsAsync(instanceId, SubFolder, masterFileNum, null);
        }
        
        /// <remarks/>
        public void GetFileInfoDetailGuidsAsync(string instanceId, string SubFolder, int masterFileNum, object userState) {
            if ((this.GetFileInfoDetailGuidsOperationCompleted == null)) {
                this.GetFileInfoDetailGuidsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFileInfoDetailGuidsOperationCompleted);
            }
            this.InvokeAsync("GetFileInfoDetailGuids", new object[] {
                        instanceId,
                        SubFolder,
                        masterFileNum}, this.GetFileInfoDetailGuidsOperationCompleted, userState);
        }
        
        private void OnGetFileInfoDetailGuidsOperationCompleted(object arg) {
            if ((this.GetFileInfoDetailGuidsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFileInfoDetailGuidsCompleted(this, new GetFileInfoDetailGuidsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteFileInfoDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteFileInfoDetails(string instanceId, string SubFolder, int masterFileNum, int[] fileDetailSeqs) {
            object[] results = this.Invoke("DeleteFileInfoDetails", new object[] {
                        instanceId,
                        SubFolder,
                        masterFileNum,
                        fileDetailSeqs});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteFileInfoDetailsAsync(string instanceId, string SubFolder, int masterFileNum, int[] fileDetailSeqs) {
            this.DeleteFileInfoDetailsAsync(instanceId, SubFolder, masterFileNum, fileDetailSeqs, null);
        }
        
        /// <remarks/>
        public void DeleteFileInfoDetailsAsync(string instanceId, string SubFolder, int masterFileNum, int[] fileDetailSeqs, object userState) {
            if ((this.DeleteFileInfoDetailsOperationCompleted == null)) {
                this.DeleteFileInfoDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteFileInfoDetailsOperationCompleted);
            }
            this.InvokeAsync("DeleteFileInfoDetails", new object[] {
                        instanceId,
                        SubFolder,
                        masterFileNum,
                        fileDetailSeqs}, this.DeleteFileInfoDetailsOperationCompleted, userState);
        }
        
        private void OnDeleteFileInfoDetailsOperationCompleted(object arg) {
            if ((this.DeleteFileInfoDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteFileInfoDetailsCompleted(this, new DeleteFileInfoDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DeleteAllFileInfoDetails", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int DeleteAllFileInfoDetails(string instanceId, string SubFolder, int masterFileNum) {
            object[] results = this.Invoke("DeleteAllFileInfoDetails", new object[] {
                        instanceId,
                        SubFolder,
                        masterFileNum});
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteAllFileInfoDetailsAsync(string instanceId, string SubFolder, int masterFileNum) {
            this.DeleteAllFileInfoDetailsAsync(instanceId, SubFolder, masterFileNum, null);
        }
        
        /// <remarks/>
        public void DeleteAllFileInfoDetailsAsync(string instanceId, string SubFolder, int masterFileNum, object userState) {
            if ((this.DeleteAllFileInfoDetailsOperationCompleted == null)) {
                this.DeleteAllFileInfoDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteAllFileInfoDetailsOperationCompleted);
            }
            this.InvokeAsync("DeleteAllFileInfoDetails", new object[] {
                        instanceId,
                        SubFolder,
                        masterFileNum}, this.DeleteAllFileInfoDetailsOperationCompleted, userState);
        }
        
        private void OnDeleteAllFileInfoDetailsOperationCompleted(object arg) {
            if ((this.DeleteAllFileInfoDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteAllFileInfoDetailsCompleted(this, new DeleteAllFileInfoDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFileInfoUrl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFileInfoUrl(string instanceId, string SubFolder, int masterFileNum) {
            object[] results = this.Invoke("GetFileInfoUrl", new object[] {
                        instanceId,
                        SubFolder,
                        masterFileNum});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFileInfoUrlAsync(string instanceId, string SubFolder, int masterFileNum) {
            this.GetFileInfoUrlAsync(instanceId, SubFolder, masterFileNum, null);
        }
        
        /// <remarks/>
        public void GetFileInfoUrlAsync(string instanceId, string SubFolder, int masterFileNum, object userState) {
            if ((this.GetFileInfoUrlOperationCompleted == null)) {
                this.GetFileInfoUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFileInfoUrlOperationCompleted);
            }
            this.InvokeAsync("GetFileInfoUrl", new object[] {
                        instanceId,
                        SubFolder,
                        masterFileNum}, this.GetFileInfoUrlOperationCompleted, userState);
        }
        
        private void OnGetFileInfoUrlOperationCompleted(object arg) {
            if ((this.GetFileInfoUrlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFileInfoUrlCompleted(this, new GetFileInfoUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetFileInfoDetailUrl", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetFileInfoDetailUrl(string instanceId, int fileInfoDetailSeq) {
            object[] results = this.Invoke("GetFileInfoDetailUrl", new object[] {
                        instanceId,
                        fileInfoDetailSeq});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetFileInfoDetailUrlAsync(string instanceId, int fileInfoDetailSeq) {
            this.GetFileInfoDetailUrlAsync(instanceId, fileInfoDetailSeq, null);
        }
        
        /// <remarks/>
        public void GetFileInfoDetailUrlAsync(string instanceId, int fileInfoDetailSeq, object userState) {
            if ((this.GetFileInfoDetailUrlOperationCompleted == null)) {
                this.GetFileInfoDetailUrlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetFileInfoDetailUrlOperationCompleted);
            }
            this.InvokeAsync("GetFileInfoDetailUrl", new object[] {
                        instanceId,
                        fileInfoDetailSeq}, this.GetFileInfoDetailUrlOperationCompleted, userState);
        }
        
        private void OnGetFileInfoDetailUrlOperationCompleted(object arg) {
            if ((this.GetFileInfoDetailUrlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetFileInfoDetailUrlCompleted(this, new GetFileInfoDetailUrlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetBaseUpdateFilesCompletedEventHandler(object sender, GetBaseUpdateFilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBaseUpdateFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBaseUpdateFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetUpdateFilesCompletedEventHandler(object sender, GetUpdateFilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUpdateFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUpdateFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetReportsUpdateFilesCompletedEventHandler(object sender, GetReportsUpdateFilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReportsUpdateFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReportsUpdateFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void NeedReloadAllFilesCompletedEventHandler(object sender, NeedReloadAllFilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class NeedReloadAllFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal NeedReloadAllFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetAppUpdaterUpdateListCompletedEventHandler(object sender, GetAppUpdaterUpdateListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAppUpdaterUpdateListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAppUpdaterUpdateListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetSubReportsUpdateFilesCompletedEventHandler(object sender, GetSubReportsUpdateFilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSubReportsUpdateFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSubReportsUpdateFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SaveFileWithShellExecuteCompletedEventHandler(object sender, SaveFileWithShellExecuteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveFileWithShellExecuteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveFileWithShellExecuteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void InitializationCompletedEventHandler(object sender, InitializationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InitializationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InitializationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BeginUploadCompletedEventHandler(object sender, BeginUploadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BeginUploadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BeginUploadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void AppendChunkCompletedEventHandler(object sender, AppendChunkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AppendChunkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AppendChunkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EndUploadCompletedEventHandler(object sender, EndUploadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EndUploadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EndUploadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SaveCompletedEventHandler(object sender, SaveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SaveAllCompletedEventHandler(object sender, SaveAllCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void SaveAllWithFileInfoMstCompletedEventHandler(object sender, SaveAllWithFileInfoMstCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SaveAllWithFileInfoMstCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SaveAllWithFileInfoMstCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void UploadFileOnlyCompletedEventHandler(object sender, UploadFileOnlyCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UploadFileOnlyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UploadFileOnlyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeleteFolderCompletedEventHandler(object sender, DeleteFolderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFolderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteFolderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeleteFilesCompletedEventHandler(object sender, DeleteFilesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFilesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteFilesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void BeginDownloadCompletedEventHandler(object sender, BeginDownloadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BeginDownloadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BeginDownloadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetChunkCompletedEventHandler(object sender, GetChunkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetChunkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetChunkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public byte[] buffer {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void EndDownloadCompletedEventHandler(object sender, EndDownloadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EndDownloadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EndDownloadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetUploadSizeLimmitCompletedEventHandler(object sender, GetUploadSizeLimmitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUploadSizeLimmitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUploadSizeLimmitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeleteFileInfoMstCompletedEventHandler(object sender, DeleteFileInfoMstCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFileInfoMstCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteFileInfoMstCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetFileInfoDetailSeqsCompletedEventHandler(object sender, GetFileInfoDetailSeqsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFileInfoDetailSeqsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFileInfoDetailSeqsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetFileInfoDetailNamesCompletedEventHandler(object sender, GetFileInfoDetailNamesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFileInfoDetailNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFileInfoDetailNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetFileInfoDetailGuidNamesCompletedEventHandler(object sender, GetFileInfoDetailGuidNamesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFileInfoDetailGuidNamesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFileInfoDetailGuidNamesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetFileInfoDetailGuidsCompletedEventHandler(object sender, GetFileInfoDetailGuidsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFileInfoDetailGuidsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFileInfoDetailGuidsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeleteFileInfoDetailsCompletedEventHandler(object sender, DeleteFileInfoDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteFileInfoDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteFileInfoDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeleteAllFileInfoDetailsCompletedEventHandler(object sender, DeleteAllFileInfoDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteAllFileInfoDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteAllFileInfoDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetFileInfoUrlCompletedEventHandler(object sender, GetFileInfoUrlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFileInfoUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFileInfoUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void GetFileInfoDetailUrlCompletedEventHandler(object sender, GetFileInfoDetailUrlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetFileInfoDetailUrlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetFileInfoDetailUrlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591